version: "3"
services:
  web:
    env_file: .env
    image: node-app
    ports:
      - "${WEBPACK_PORT}:${WEBPACK_PORT}"
    volumes:
      - node_modules:/app/node_modules:ro
      - .:/app:ro
volumes:
  node_modules:
