# Intended for Development Environment - Not Production

version: "3.4"
services:
  web:
    env_file: .env
    build:
      context: .
      target: build
    ports:
      - "${WEBPACK_PORT}:${WEBPACK_PORT}"
    networks:
      - backend
    volumes:
      - node_modules:/app/node_modules:ro
      - .:/app
    depends_on:
      - database
  database:
    env_file: .env
    image: couchdb:2.1.1
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - backend
    volumes:
      - database:/app/data

networks:
  backend:

volumes:
  database:
  node_modules:
