version: "3"
services:
  web:
    env_file: .env
    image: node-app
    ports:
      - "${WEBPACK_PORT}:${WEBPACK_PORT}"
    volumes:
      - node_modules:/app/node_modules:ro
      - .:/app
  database:
    image: couchdb:2.1.1
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - database:/app/data
volumes:
  database:
  node_modules:
