version: "3.4"
services:
  web:
    image: dockercouchdb_web:production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.25"
          memory: 75M
      restart_policy:
        condition: on-failure
    ports:
      - "80:2305"
    networks:
      - backend
    depends_on:
      - database
    environment:
      PORT: 2305
      HOST: 0.0.0.0
      NODE_ENV: production
      DATABASE_PORT: 5984
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: /run/secrets/db_admin_password
    secrets:
      - db_admin_password

  database:
    image: couchdb:2.1.1
    networks:
      - backend
    volumes:
      - database:/app/data
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: /run/secrets/db_admin_password
    secrets:
      - db_admin_password

networks:
  backend:

volumes:
  database:
  node_modules:

secrets:
  db_admin_password:
    file: .secrets/db-admin-password.txt
